### ISSUE TITLE
Unable to use this alongside react-native-modal. Is this a fork of that repo?

### ISSUE THREAD

**Issue by MossP** [maxs15/react-native-modalbox#1]
Hi, great plugin. I tried to use it in my project but I get duplicate linker errors. This appears to be because I'm using react-native-modal by @brentvatne also. Is this a fork? I'm guessing the two can't be run alongside each other then?

**Comment by maxs15** [comment]
Hi,
This is because both modules have a dependency on [react-native-overlay](https://github.com/brentvatne/react-native-overlay).
I'm not sure what is the best way to avoid conflicts with modules sharing the same dependency.
@brentvatne, any idea ?

**Comment by maxs15** [comment]
Alternatively you can still not include RNModalbox.xcodeproj, you just won't be able to display the modal on top of the status bar.

**Comment by brentvatne** [comment]
No good solution for this at the moment, you can just skip including one of the xcodeproj's for now as @maxs15 suggested :(

**Comment by MossP** [comment]
Thanks guys. I see this could become more of an issue over time as more components are released. Maybe we need an 'awkward' list to go with your 'difficult' list @brentvatne? I should be able to get around this though. Thank you, both.

**Comment by brentvatne** [comment]
@MossP - this is more of a problem with the packaging and distribution of libraries, not the kind of problems I had in mind for the list - was thinking more of UI that can be done with pure native but seems so far difficult to achieve with the tools that React Native provides
