### ISSUE TITLE
Modal appears below Button that triggers it.

### ISSUE THREAD

**Issue by maotora** [maxs15/react-native-modalbox#105]
Hi.

My Modal appears below the `Button` that trigger it opening.

I'm not sure how `Modal` is suppose to work when nested in containers of other UI components.

A quick look of my code

```jsx
<Content>
    <Grid >
        <Row>
            <Col>
                <Text style={styles.textStyles}> some words go here... </Text>
            </Col>
        </Row>
        <Row>
            <Col>
                <Button block onPress={this.openAddDevice} style={{margin: 10}}>
                    <Icon name="md-add" />
                    Add Devices
                </Button>
            </Col>
        </Row>
    </Grid>
    <Modal onOpened={this.logger} backdrop={true} ref={"modal"}>
        <AddDevices />
    </Modal>
</Content>

const styles = StyleSheet.create({
    textStyles: {
        fontSize: 28,
        lineHeight: 30,
        color: 'white',
        textAlign: 'center',
        padding: 10,
        marginBottom: 10
    }
});


```

I'm using **NativeBase** *which is giving those `<Content />` & `<Container />`* and using **react-native-easy-grid** *giving me the `<Grid />` elements as seen there*.

Problem comes, when i click the button `<Modal />` **covers** everything except the `<Button />` component which is inside `<Row />` & `<Col />` as other hidden elements.

I fail to understand how to remove it please help.

![This is how it looks like](https://cloud.githubusercontent.com/assets/5174884/21286573/f4b9b8c4-c468-11e6-9151-b3f532ddda32.png)

**Comment by maotora** [comment]
So, it turns out **Android**'s `<Button />`'s are set with some higher `elevation`.

Setting this to `<Button style={{elevation: 0}} ... />`solved my issue.

Thanks for this beautiful library.

**Comment by vzhen** [comment]
I having the same issue. Android 5.1 here.
Clicked button is on top of modal from bottom.
I tried `<Button style={{elevation: 0}} ... />` but not working

**Comment by maotora** [comment]
@vzhen Hey man!

I regret to inform you that i don't have an answer to that, But!

I found out the solution because i posted on the react-native group on facebook.

Try your [there](https://www.facebook.com/groups/react.native.community/)!

Goodluck!

**Comment by vzhen** [comment]
@maotora Can you post the excalty post link?  The current link is just link to facebook group or any keyword so i can search for it?

**Comment by maotora** [comment]
@vzhen yes, that's me.

and yeah it's just a group on facebook called *react-native community* i think.
