### ISSUE TITLE
Does not cover the Status Bar?

### ISSUE THREAD

**Issue by twist900** [maxs15/react-native-modalbox#109]
In the examples from the README (GIFs) the modal is displayed over the status bar. When I run the examples provided by the project I see the modal underneath the status bar, is it possible to display it above? (react-native 0.40)

**Comment by progrmor** [comment]
Leaving a comment here since I have the same issue but with a button and an Input field.

**Comment by andredaniel** [comment]
The same issue here. Modal is appearing behind  List, tabBar and headerBar. I'm using Expo and nativebase.

**Comment by kjunggithub** [comment]
Same issue here, zIndex does not help.

**Comment by kjunggithub** [comment]
@progrmor @andredaniel see this PR https://github.com/maxs15/react-native-modalbox/pull/124. Doing this solves the issue where inputs and buttons would show on top of the backdrop.

**Comment by jaumebosch** [comment]
Same problem here, if you set "entry={"top"} it appears over the statusbar, but if the modal is inside a scrollview, works pretty well, unless you swipe the scroll....

**Comment by TalkTek** [comment]
same issue here, does anybody know how to fix it?

**Comment by joey3060** [comment]
same issue here, does anybody know how to fix it?

**Comment by maxs15** [comment]
Sorry guys for taking this long, the PR has been merged 👍 
Will be available in the next release

**Comment by chawkibenalaya** [comment]
add this props and it will work coverScreen={true}

**Comment by mym0404** [comment]
![image](https://user-images.githubusercontent.com/33388801/103876278-cb7c8d80-5116-11eb-9579-0b38433aaac2.png)

- Android
- 2.0.0

```tsx
<Modal
      ref={modal}
      entry="top"
      position="center"
      style={{
        width: dialogWidth,
        height: 'auto',
        minHeight: dialogMinHeight,
        ...Elevation[8],
        borderRadius: (30).d(),
        padding: (26).d(),
      }}
      swipeToClose={false}
      backdropPressToClose={false}
      backButtonClose={false}
      coverScreen={true}
    >
```
