### ISSUE TITLE
Doesn't work on Android

### ISSUE THREAD

**Issue by cmmouritsen** [maxs15/react-native-modalbox#11]
I'm not sure if it's supposed to or not. It seemed from the comments on some commits that it should, but it doesn't work on Android.

**Comment by maxs15** [comment]
What is exactly the issue on Android, do you have any error ?

**Comment by cmmouritsen** [comment]
I don't see an error. Just the modal dialog doesn't display. I even tried to run the sample. It seems like a pixel-sized orange dot shows, but the dialog doesn't display at all.

**Comment by maxs15** [comment]
You're right there is actually some issues on Android.
I'm going to take a look at that

**Comment by maxs15** [comment]
Please try again the last version, it should work better :)

**Comment by cmmouritsen** [comment]
Awesome. Thanks. Should it be available via npm?

**Comment by maxs15** [comment]
Yes, it is available now on npm

**Comment by cmmouritsen** [comment]
It works. Thanks!
