### ISSUE TITLE
Modal has a white backing, can't offset with margin

### ISSUE THREAD

**Issue by ryanhomer** [maxs15/react-native-modalbox#110]
In the source code there is:
```
  wrapper: {
    backgroundColor: "white"
  },
```
Which makes the background of the modal itself white. So if I make the background of my view some other colour, say blue, and set a margin, it'll expose the white beneath it instead of showing what's behind the entire modal itself.

Any reason in particular why this choice was made? I feel it should be "transparent".

**Comment by maxs15** [comment]
White is the default color indeed, just overrider the style of the Modal to change the backgroundColor

**Comment by ryanhomer** [comment]
That works! Thanks.
