### ISSUE TITLE
Option for built-in close button

### ISSUE THREAD

**Issue by peacechen** [maxs15/react-native-modalbox#113]
It would be helpful to provide a stock close button for the modal.  This is a common UI for modals and results in repeated boilerplate for those using this library who need a close button.  It is required when the modal takes up the entire screen and swipe-to-close is disabled.

**Comment by maxs15** [comment]
Hey @peacechen, the issue is that the close button that you want to choose is up to you, we cannot force any icon.
Just create a wrapper with the ``backdropContent``property
