### ISSUE TITLE
backdropPressToClose isn't work

### ISSUE THREAD

**Issue by zuzuviewer** [maxs15/react-native-modalbox#115]
my code:
`<Modal style={[Style.modalView]} backdropPressToClose={true} backdrop={true}  position={"center"} ref={"modalDialog"}>`
but when I press on backdrop ,the modal didn't close.In additional,swipe down to close is work.

**Comment by shinework** [comment]
Same case for me :)

**Comment by caphun** [comment]
any update on this?

**Comment by wbattel4607** [comment]
+1

**Comment by maxs15** [comment]
Fix Merged
