### ISSUE TITLE
RN 0.13.0-rc Errors? 'Cannot Read Property 'stop' of undefined

### ISSUE THREAD

**Issue by MossP** [maxs15/react-native-modalbox#12]
I'm experiencing a few errors on RN 0.13 (I came from v0.9 so cannot see when these were introduced)

Opening modals with content in still close immediately similar to https://github.com/maxs15/react-native-modalbox/issues/6. Also Sometime get 'Cannot Read Property 'stop' of undefined index.js:178.

Should this work on RN 0.13.0-rc? or am I getting ahead of myself?

**Comment by MossP** [comment]
Just an addition to the error report. The crash is inconsistent. I can get it sometimes on clean load, then not on others.

**Comment by MossP** [comment]
Typical that as soon as I post I find a few things that help.

The error appears to have been happening because I using the re.open() method, but not setting the isOpen prop first. This causes the modal to instantly close. Sometimes before the animation is even setup, causing the crash.

Most likely because I am mixing and matching which method to use for modals. Setting them to one of either refs.X is isOpen should fix this.

**Comment by maxs15** [comment]
I'm glad you found the problem.
