### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by iRoachie** [maxs15/react-native-modalbox#122]
Hey are you interested in having typescript typings for this library? For those using React native with typescript. I've already started on them in my personal projects.

**Comment by iRoachie** [comment]
Completed. `npm i --save @types/react-native-modalbox`

**Comment by hironarita** [comment]
@iRoachie Could you add keyboardTopOffset to the definition file?

**Comment by iRoachie** [comment]
@hironarita PR is here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21791
