### ISSUE TITLE
Warning: BackAndroid is depricated. Please use BackHandler instead. 

### ISSUE THREAD

**Issue by chetankotkar** [maxs15/react-native-modalbox#128]
I am using this Lib. Updated to react-native 0.44.0. Am getting this warning every time. Can you please update this one.

**Comment by iRoachie** [comment]
@chetankotkar Sent a PR

**Comment by iRoachie** [comment]
@chetankotkar You can use my fork until the PR is merged https://github.com/iRoachie/react-native-modalbox.git
