### ISSUE TITLE
Multiple Modals - No Longer Supported?

### ISSUE THREAD

**Issue by MossP** [maxs15/react-native-modalbox#13]
I have an app that has a Modal but it is possible to pull another Modal up on top of this. This used to work but now seems to not do anything?

**Comment by maxs15** [comment]
You're right, I didn't try this case.
It seems that this is currently not possible to have multiple react-native Modal components.
I opened an issue: https://github.com/facebook/react-native/issues/3445
Like the other issue you can use the v1.1.5, I have to think if we should stick with the react-native Modal component, maybe too soon ?

**Comment by MossP** [comment]
It's good to push forward though. For my project I have had to drop back to 1.1.5 for now as it relies on those two features but I'm probably a small use case for multiple modals.

Love the work you're doing though. Thanks @maxs15 !
