### ISSUE TITLE
Modal offset when screen rotated

### ISSUE THREAD

**Issue by peacechen** [maxs15/react-native-modalbox#137]
Similar to #82 and #94, modalbox is offsetting the modal after screen rotation.  Initially it opens ok:
![image](https://cloud.githubusercontent.com/assets/6295083/26358296/b6eb4e04-3f97-11e7-851b-50ea663ec359.png)

but after rotation it's incorrect:
![image](https://cloud.githubusercontent.com/assets/6295083/26358361/f27e8918-3f97-11e7-9570-1fb8862708ac.png)

Rotating it back doesn't fix it.  The modal must be dismissed and re-opened for it to center properly.

A potential caveat is that our app is using RN 0.34.  However the onLayout behavior remains the same for 0.4x.

**Comment by peacechen** [comment]
State should not be directly mutated at
https://github.com/maxs15/react-native-modalbox/blob/master/index.js#L315

> [Never mutate this.state directly, as calling setState() afterwards may replace the mutation you made. Treat this.state as if it were immutable.](https://facebook.github.io/react/docs/react-component.html#state)

What is the purpose of the empty setStates at
https://github.com/maxs15/react-native-modalbox/blob/master/index.js#L411
and
https://github.com/maxs15/react-native-modalbox/blob/master/index.js#L238

**Comment by mikaelrosquist** [comment]
Experiencing the same issue. Any ideas on how to solve it?

**Comment by mikaelrosquist** [comment]
Solved it by replacing the direct mutation of state to `setState` on lines 315 and 316, as @peacechen mentioned above.

This:
```
// If the dimensions are still the same we're done
if (height !== this.state.height) this.state.height = height;
if (width !== this.state.width) this.state.width = width;
```
Should be:

```
// If the dimensions are still the same we're done
if (height !== this.state.height) this.setState({height: height})
if (width !== this.state.width) this.setState({width: width})
```

**Comment by peacechen** [comment]
Thanks @mikaelrosquist.  Created PR #141 with your recommended fix.  Did a minor refactor to call setState once instead of twice since height & width both change on rotation.

**Comment by maxs15** [comment]
Thanks @peacechen, going to merge the PR, will be available in the next release
