### ISSUE TITLE
Doesnt work while putting it inside TabNavigator

### ISSUE THREAD

**Issue by Tom29** [maxs15/react-native-modalbox#142]
I'm using TabNavigator and use modalbox inside one tab.
Rendering ListView, or FlatList displays blank page. Otherwise, it works.

**Comment by Tom29** [comment]
I found out the error comes from `screen`. You use `var screen = Dimensions.get('window');` to determine the height of modal. Its wrong.

The height of modal in TabNavigator = screen height - tabbar height.

**Comment by maxs15** [comment]
hmmm weird.. check out the onContainerLayout function.
screen.height is the default value, but it should be updated if the height is different than screen.height

**Comment by Tom29** [comment]
@maxs15 I found the fix version:
https://github.com/prtkkmrsngh/react-native-modalbox/blob/master/index.js
It works perfectly on TabNavigator by using modal inside

**Comment by maxs15** [comment]
I see now, because you didn't declare the Modal in your Root View, if you do it should work as well.
This fork, use the Modal Component that launch a new window on top of the current one, will probably integrate this feature later

**Comment by maxs15** [comment]
The property has been added in the last release just use ``coverScreen={true}``
I'm closing the issue

**Comment by zhuyifan2013** [comment]
@maxs15 coverScreen={true} use the `modal` component from react-native, I am afraid there will be some other bugs in future.
