### ISSUE TITLE
Is there a way to avoid closing the modal, like a "isClosable" attribute so that the modal stays open and the user cannot close it?

### ISSUE THREAD

**Issue by eMatsiyana** [maxs15/react-native-modalbox#15]

**Comment by maxs15** [comment]
Unfortunately not currently.
But this is a great idea @eMatsiyana , will look at that and push it in the next release

**Comment by michaelwschultz** [comment]
@eMatsiyana couldn't you simply turn off the swipe to close and not include a close button?

**Comment by eMatsiyana** [comment]
@michaelwschultz ... That would have worked but unfortunately, after turning off the swipe, " swipeToClose={false}" doesn't turn off the close function:

If you tap outside the modal, it still closes.

**Comment by maxs15** [comment]
Yes, currently you cannot deactivate the swipeToClose feature after the component has been mounted.
I'm will look for a fix this week-end

**Comment by eMatsiyana** [comment]
That's perfect @maxs15 ... Looking forward to the fix :+1:

**Comment by maxs15** [comment]
The isDisabled property has been added in the last version 1.2.2.
It should answer your needs :)
I'm closing the issue
