### ISSUE TITLE
Allow no animated backdrop opacity

### ISSUE THREAD

**Issue by bradbumbalough** [maxs15/react-native-modalbox#158]
Hello,

Thanks for this great repo. I'm using [react-native-blur](https://github.com/react-native-community/react-native-blur) as the backdrop, and it has a [known issue](https://github.com/react-native-community/react-native-blur/issues/126) that it can't be wrapped in a view with an opacity less than 1. I wanted to know if you'd be open to a PR that would allow you to not animate the backdrop opacity. Or maybe even start thinking through supporting blur backdrops as a first class citizen.

Thanks!

**Comment by mundiallover** [comment]
+1
