### ISSUE TITLE
Can't scroll within' the modal

### ISSUE THREAD

**Issue by JimmyMow** [maxs15/react-native-modalbox#16]
Maybe I am doing something wrong, but for some reason ScrollView is not working inside of a modal, and I can't adjust the height. For example when a form input is touched and I'd like to adjust the View height in relation to the keyboard.

**Comment by maxs15** [comment]
It is working on my side, but if you are using the swipeToClose option you should use the swipeArea property to define the height of the swipe zone.
You won't be able to scroll in the swipe area

**Comment by JimmyMow** [comment]
Wow, not smart on my part haha. Thanks for the fast and accurate reply my friend. Cheers
