### ISSUE TITLE
All animations are disabled

### ISSUE THREAD

**Issue by MeghdadHadidi** [maxs15/react-native-modalbox#178]
Hi, 
In all states of my modals (Opening, Closing, onSwipeClose, ...) no animation is applied at all. 
I tried to add Easing library from react-native. But it does not work 
Modal appears suddenly after default animation duration mentioned in config.
Any idea?

**Comment by bvv218** [comment]
I suddenly started to have the same problem. Did you solve this?

**Comment by MeghdadHadidi** [comment]
It was just happening on emulator. On real device it works fine for me
