### ISSUE TITLE
Modal opens multiple times

### ISSUE THREAD

**Issue by clementino36** [maxs15/react-native-modalbox#181]
Hi,
The `isOpen` prop of my modal is managed by a redux action I've created so that I could open the modal easily from anywhere in my app. I'm setting the `isOpen` value to false whenever the `onClosed` prop is called. I clearly see in my redux state that the value is correct whenever I open or close the modal.

The problem is that when I navigate to another component and then come back to the component that contains the modal, if I open the modal, it opens multiple times over itself. If I do that several times, it'll take forever for the modal to open since there will be several layers of the same modal over each other...
Hope this is clear enough.

**Comment by lishoulong** [comment]
I also encounter the same problem, every time I close the modal, it will leave off a modal layer, then when you open and close the modal multiple times, the layers overlap.

**Comment by wkoutre** [comment]
@clementino36 I'm confused.

When you write: 

> The problem is that when I navigate to another component and then come back to the component that contains the modal, if I open the modal, it opens multiple times over itself.

If you're putting `isOpen` in a reducer, then to me, it makes sense that the Modal is a child of the `Provider`. Therefore, it shouldn't be in the child of any other Component. Navigating while the Modal is open won't result in the UI on the screen changing since the Modal isn't part of the navigation stack.

**Comment by clementino36** [comment]
I'm not sure i understood everything you explained but I think that you pointed the problem out. The modal was situated in a child component. I put it in my main component and right now everything seems to be fine. I'll come back if i experience a similar issue. Thank you!
