### ISSUE TITLE
Touchable* doesn't work on iPhone 6s

### ISSUE THREAD

**Issue by h3l** [maxs15/react-native-modalbox#19]
on iPhone 6s ,react-native-modalbox can't response Touch event,
even the third example(Position centered + backdrop + disable ) doesn't work.

I have check the index.js, I found that it is the Animated.View affect this.But I am not similar to the Animated.

related issue closed #10

**Comment by maxs15** [comment]
Hey @h3l,
It seems like this is a bug related to react native with the 3D touch:
https://github.com/facebook/react-native/issues/3082
Could you please check the potential fixes by the members ?
I don't have any iphone 6s for testing yet.

Thanks

**Comment by h3l** [comment]
@maxs15 
that's doesn't fix my problem,
But I find a not beautiful way to solve this problem.
just use onPressIn not onPress in Touchable*.

Thank you~

**Comment by maxs15** [comment]
Ok, we could push this fix if it solves the issue..
Is everything working with this change ? If I understood the only problem you have is with the backdrop right ?

**Comment by h3l** [comment]
The backdrop is ok, but the something like TouchableWithoutFeedback doesn't work in Modal.

For example,
the third example(Position centered + backdrop + disable ) Button does not work,it can't toggleDisable.
here is the code. 

```
        <Modal style={[styles.modal, styles.modal3]} position={"center"} ref={"modal3"} isDisabled={this.state.isDisabled}>
          <Text style={styles.text}>Modal centered</Text>
          <Button onPress={this.toggleDisable} style={styles.btn}>Disable ({this.state.isDisabled ? "true" : "false"})</Button>
        </Modal>
```

**Comment by maxs15** [comment]
Ohh okay, it's more a problem with the button component ?

**Comment by h3l** [comment]
Yes, but it seems not only the bottom component's problem,
it's the problem all TouchableWithoutFeedback, TouchableOpacity and so on.

All those component can't response onPress event well, but onPressIn and onPressOut work well.

**Comment by maxs15** [comment]
Ok I see.
However, is the button working properly outside of the modal ?

**Comment by h3l** [comment]
I may have another more beautiful way to solve this, but now, I have to finish my work.
I will try to fix it as soon as possible.

**Comment by h3l** [comment]
Yes, everythings works well outside of the modal.

**Comment by vitorhorta** [comment]
Same issue here. 
Touchable doesn't work on Modal and Text Inputs doesn't work as well.
I am testing on Android emulator (genymotion) and tried onPressIn and onPressOut but with no success.

**Comment by maxs15** [comment]
This should be fixed in the new version 1.2.4, I'm closing the issue.

**Comment by maxs15** [comment]
Hey @h3,l if you have some time could you tell me if the 3D touch is working on the last version ?
Would be awesome, I had to do some modifications related to the changes we've made to fix your issue

**Comment by h3l** [comment]
@maxs15 i have to go to sleep right now, i will test the last version in about 12 hours and git you a response.

**Comment by maxs15** [comment]
No worry, no rush :) Thanks for the help

**Comment by h3l** [comment]
@maxs15 i have test the last version Example on my iPhone 6s, everything is ok.
: )

**Comment by SudoPlz** [comment]
@maxs15 How did you resolve the 3d touch problem?

I've got absolute views but can't for the love of me tap them on iPhones 6s and above when the 3d touch setting is enabled..!

Any ideas?

**Comment by cinder92** [comment]
@h3l thank you, sure, is not beautify but, it works
