### ISSUE TITLE
Working example? How to setup backdrop?

### ISSUE THREAD

**Issue by aksonov** [maxs15/react-native-modalbox#2]
I can't use it like shown in video - how to setup backdrop?

**Comment by maxs15** [comment]
Well, what is your problem ?
There is no built-in backdrop for now, but I will add this feature soon.

**Comment by aksonov** [comment]
I don’t know how to add backdrop for latest version correctly - looks like ‘absolute’ styling works differently now for deep trees . react-native-modal is broken as well (it worked well for 0.6.0)...

**Comment by maxs15** [comment]
@aksonov check the new version [1.1.0](https://github.com/maxs15/react-native-modalbox/releases/tag/v1.1.0)
I added the backdrop feature, a working example and much more !

**Comment by aksonov** [comment]
Thanks, works perfect!
