### ISSUE TITLE
react-native-modalbox does not work in react-native 0.16.0

### ISSUE THREAD

**Issue by easyfan** [maxs15/react-native-modalbox#23]
Within react-native 0.16.0, the modal box does not work at all. While trying to open the Modal in the project with official sample code,  error messages will given as below:
<img width="429" alt="screen shot 2015-12-07 at 1 01 41 pm" src="https://cloud.githubusercontent.com/assets/7017849/11619473/622e4c3e-9ce3-11e5-9687-f78fbee3c51c.png">

**Comment by maxs15** [comment]
You're right, same on my side.
I will have to investigate further, I'm not sure where it comes from yet, any idea?
Could be a bug introduced in React 0.16.

**Comment by malinthe** [comment]
I'm having the same issue. Definitely started with 0.16

**Comment by easyfan** [comment]
Seems because that since 0.16, the react native does not tolerate the usage of UnimplementedView, and  through exception when trying to use. 
And it is my question for long time: why you just using UnimplementedView for Android version of react-native-overlay? Any special reason?
Further more, I made some try on my side, that change the reference from RNOverlay to a common view in the react-native-overlay.render, like below:
```
render() {
    var {
      isVisible,
    } = this.props;

    if (this.props.isVisible) {
      return (
        <View isVisible={true} style={styles.container} pointerEvents="none" aboveStatusBar={this.props.aboveStatusBar}>
          {React.Children.map(this.props.children, React.addons.cloneWithProps)}
        </View>
      );
    } else {
      return <View />;
    }
  }
```
With above changes, the modal box could be presented normally, but all the mouse event on the modal box lost.

**Comment by maxs15** [comment]
Okay, looks like it is related to the [react-native-overlay](https://github.com/brentvatne/react-native-overlay) component.
I'm going to think about an alternative, will push a fix soon

**Comment by maxs15** [comment]
Please check the new version v1.2.5, should work now on react native 0.16 !

**Comment by maxs15** [comment]
I'm going to close this issue, if you still have problems let me know

**Comment by easyfan** [comment]
Verified. Great work! thanks!
