### ISSUE TITLE
The modal box delays when opening whenever its fetching or displaying large volume list (like countries)

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [maxs15/react-native-modalbox#253]
The modal box delays when opening whenever its fetching or displaying large volume list (like countries). Is there anyways to make the model appear first and then load the data? Or how to stop the delays

**Comment by abdullahizzuddiin** [comment]
> Is there anyways to make the model appear first and then load the data?

Have you give `onOpened()` prop a shot? Look at https://github.com/maxs15/react-native-modalbox#events ?

be careful, #257 - onOpened() Call Twice

**Comment by ManigandanRaamanathan** [comment]
fixed by using flatlist
