### ISSUE TITLE
Is it possible to remove the overlay?

### ISSUE THREAD

**Issue by xstable** [maxs15/react-native-modalbox#254]
I use the modalBox as kind of Media-Toolbar.

I let it open at the bottom of the screen. Is it possible to remove the dark layer with opacity which is outside of my modal (the red framed area)
![image](https://user-images.githubusercontent.com/1778068/49038409-2cf27400-f1bd-11e8-8d10-970f18a490ed.png)

If not, it would be a great feature to make this overlay optional!

**Comment by pepincho** [comment]
Hi @xstable, Did you find a way to fix it? I'm also trying to accomplish similar behavior.

**Comment by xstable** [comment]
Yer, I solved it by using `isDisabled` to prevent each action on it:

```
<Modal
          style={[styles.audioToolbarModal, styles.audioToolbarBottomModal]}
          position="bottom"
          backdrop
          swipeToClose={false}
          coverScreen
          onOpened={() => this.startRecording()}
          isDisabled={modalIsDisabled}
          ref={(ref) => { this.audioToolbar = ref; }}
        >
```
