### ISSUE TITLE
BackAndroid causing error in RN 0.58.0

### ISSUE THREAD

**Issue by ryanhomer** [maxs15/react-native-modalbox#256]
The fix in #136 removed the deprecation warning in prior versions of RN. However, with 0.58.0 around the corner, this API has been completely removed which will cause an error. `BackAndroid` now needs to be completely removed from the code.

**Comment by nigelpasco** [comment]
Simply removing reference to BackAndroid (and leaving BackHandler) in the index.js fixes it up, it seems.

**Comment by maxs15** [comment]
Fix merged in 1.7.0 :)
