### ISSUE TITLE
add property for controlling animation speed

### ISSUE THREAD

**Issue by bodyflex** [maxs15/react-native-modalbox#26]
awesome component! only thing that I missed was controlling the speed of the animation.

**Comment by swain** [comment]
+1

**Comment by maxs15** [comment]
Indeed we could add this property.
I'm gonna check that after holidays, but if you want to add this feature any PR is welcomed :)

**Comment by bodyflex** [comment]
see https://github.com/maxs15/react-native-modalbox/pull/27
