### ISSUE TITLE
Bug: Fix animation getting stuck when swipeThreshold not reached

### ISSUE THREAD

**Issue by JohnWelle** [maxs15/react-native-modalbox#284]
Hi,

We are currently experiencing issues with the swipe animation getting stuck if the swipeThreshold has not been reached. Have tested the following PR which resolves the issue: https://github.com/maxs15/react-native-modalbox/pull/278

Would be great if you could look into this and see if it can be merged in to resolve this issue. #

**Comment by maxs15** [comment]
Released in v2.0.0
