### ISSUE TITLE
How to use in Functional Component using hooks?

### ISSUE THREAD

**Issue by basha777** [maxs15/react-native-modalbox#286]
I am trying to use react-native-model-box in a functional component any help is appreciated.

**Comment by MrCreeper1008** [comment]
You use it just like you would in class components. What difficulties are you facing when using it with functional components?

**Comment by claudioviola** [comment]
I tried to wrap it in my functional component.
In my functional component I used prop forwardRef and pass the ref to ModalBox ref,
But there was a red screen error

**Comment by pdSatyam** [comment]
const someFuncComp=()=>
{
const addModal=useRef(null);  //creates a reference which doesn't instantiate re-renders.
return 
(<..>.....Your code .</..>

<AddModal ref={addModal} navigation={props.navigation} parentCallback = {callbackFunction} >
</AddModal>
)

You can try with React.createRef() too , it creates a new ref everytime

**Comment by soban1234** [comment]
import the UseRef Hook
import React, { useRef } from 'react';

const ref = useRef();

in the Modal prop, refer to the ref

<Modal ref={ref}>
{children}
</Modal>

<Button title="Modal Open" onPress={() => ref.current.open()}
 />
