### ISSUE TITLE
isOpen={true} does not work

### ISSUE THREAD

**Issue by jaulz** [maxs15/react-native-modalbox#3]
Unfortunately ```isOpen={true}``` does not work as expected i.e. does not open directly and instead one has to click another time on the trigger element.

**Comment by maxs15** [comment]
Did you include RNModalbox.xcodeproj ?

**Comment by jaulz** [comment]
Sure, otherwise it won't open on the second click 😉

**Comment by maxs15** [comment]
@jaulz check the new version [1.1.0](https://github.com/maxs15/react-native-modalbox/releases/tag/v1.1.0), it should fix your issues :)

**Comment by aksonov** [comment]
isOpen property still doesn't work. I even don't see how it is used

**Comment by maxs15** [comment]
Check the last version release note.
The isOpen property has been removed in the v1.1.0, I decided to expose the `open()` and `close()` method instead to make things easier.
Check the Example to see how it is working.

**Comment by aksonov** [comment]
Maybe it is not good idea. Sometimes we need to open modal automatically after launch - i.e. depending state of modal from state of parent component.

**Comment by maxs15** [comment]
In the majority of cases, it makes things easier.
Because before you had to update the modal state in the parent controller on every internal close (swipe down, backdrop click...).
You can still open the modal depending on the parent state, just use the `componentWillReceiveProps` method.

**Comment by aksonov** [comment]
OK, thanks. No problem here, please check another critical issue #6
