### ISSUE TITLE
How to use on android Can you point in detail

### ISSUE THREAD

**Issue by mvpdream** [maxs15/react-native-modalbox#30]
first,npm 
then?????????

**Comment by maxs15** [comment]
Please check the Example folder

**Comment by mvpdream** [comment]
only ios

**Comment by maxs15** [comment]
The index.android.js require the index.ios.js, it's the same code.

**Comment by mvpdream** [comment]
react-native-modalbox for Android,Don't need to modify the settings.gradle,AndroidManifest.xml ,build.gradle?????

**Comment by maxs15** [comment]
Nope, you don't have to do anything else, the module doesn't require any native component.

**Comment by mvpdream** [comment]
Ok, I try

**Comment by mvpdream** [comment]
Although the index.js in the directory. Js But the Example/index. ios. js, for android too?and Between them is how to reference??

**Comment by maxs15** [comment]
Android will automatically require the index.android.js.
If you never used RN for android before I would advise you to read first all the docs available, especially the well made RN website: http://facebook.github.io/react-native/docs/getting-started.html

**Comment by mvpdream** [comment]
How I want to ask the index. ios. Js reference under the root directory of the index. Js

**Comment by mvpdream** [comment]
I have just tried, the android not make prompt:Requiring unknown module"react-native-modalbox".if you are sure the module is there,try restarting the packager

**Comment by maxs15** [comment]
``npm install react-native-modalbox``
Restart the react-native script

**Comment by mvpdream** [comment]
Can you give me a button component used in your project to download address?

**Comment by maxs15** [comment]
I'm using https://github.com/ide/react-native-button in the example.
If you have any question that is not related to the modalbox component, please ask on stackoverflow.
I'm closing this issue.
