### ISSUE TITLE
Reset back to original position when the swiped distance isn't long enough

### ISSUE THREAD

**Issue by msqar** [maxs15/react-native-modalbox#301]
Hello, I was thinking that would be a cool idea to bounce the modal back to the original position when the swipe distance isn't long enough to actually close it, this distance value would be the threshold value in this component.

Would it be hard to implement this behaviour? or is there a way to make it happen?

Thanks in advance. And I love this lib so far :) great job.

**Comment by msqar** [comment]
Okay after checking the code, I noticed it was doable really easy by removing this else if validation:

`if (!this.state.isOpen) ` within onPanRelease method:

Would look like this:
```
    var onPanRelease = (evt, state) => {
      if (!inSwipeArea) return;
      inSwipeArea = false;
      if (this.props.entry === 'top' ? -state.dy > this.props.swipeThreshold : state.dy > this.props.swipeThreshold)
        this.animateClose();
      else {
        this.animateOpen();
      }
    };
```

**Comment by claudioviola** [comment]
It works! Thanks!
@msqar thanks for the solution
Did you edit the node_module index.js file , creating a fork or other solution?

I don't like change the node module file

thanks again!

**Comment by msqar** [comment]
@claudioviola nope, i haven't created a PR for this. I had this modalbox long ago already as part of my components because i already made some modifications to the original before.

**Comment by claudioviola** [comment]
Hello @maxs15 
Thanks for you great modal!

Would you think to fix this issue?
The solution proposed by @msqar works very nice!

Thank you!
