### ISSUE TITLE
Two warning

### ISSUE THREAD

**Issue by orzhtml** [maxs15/react-native-modalbox#312]
"react": "16.11.0"
"react-native": "0.62.0-rc.5"
"react-native-modalbox": "^2.0.0"

`<Modal style={[styles.modal, styles.modal2]} backdrop={false}  position={"top"} ref={"modal2"}>
          <Text style={[styles.text, {color: "white"}]}>Modal on top</Text>
        </Modal>`

1、Animated.event now requires a second argument for options 

2、Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

**Comment by ghasemikasra39** [comment]
I have the same issue

**Comment by orzhtml** [comment]
@maxs15

**Comment by showtan001** [comment]
same issue+++++

**Comment by showtan001** [comment]
@orzhtml  @ghasemikasra39  
`const animEvt = Animated.event([null, {customY: position}]);`   => 
`const animEvt = Animated.event([null, {customY: position}], {useNativeDriver: true});`

**Comment by ghasemikasra39** [comment]
Dear @showtan001 
Thank you for your answer. However, your answer is not clear. Please provide us with step by step modification, with reference to the files that must be modified.

**Comment by showtan001** [comment]
@ghasemikasra39 
change “node_modules/react-native-modalbox/index.js”, About line 366.

**Comment by maxs15** [comment]
Fix deployed in 2.0.1
