### ISSUE TITLE
 Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

### ISSUE THREAD

**Issue by virtualvivek** [maxs15/react-native-modalbox#313]
## ModalBox 
Showing YellowBox Warning Should use `useNativeDriver` in my current react-native 
## Using react-native release - "16.13.1"

**Comment by orzhtml** [comment]
Duplicate of #312

**Comment by joaovictorcosta** [comment]
Estou com o mesmo problema

**Comment by joaovictorcosta** [comment]
Me too have this problem!

**Comment by edritech93** [comment]
same for me

**Comment by tischenkoa** [comment]
fixed this problem
https://github.com/maxs15/react-native-modalbox/pull/315/commits/50979244a4cab2488c38f5bae43ce20d7a915171

**Comment by cedricjacobs** [comment]
When I integrate this solution in my code, I get an error when I try to implement swipeToClose modals. 

![Simulator Screen Shot - iPhone 11 - 2020-04-24 at 11 12 38](https://user-images.githubusercontent.com/12216776/80195694-87933800-861c-11ea-8be0-b87038200a5f.png)
.

**Comment by ghasemikasra39** [comment]
Same here

**Comment by chahinaghrim** [comment]
same for me

**Comment by tmoutinho** [comment]
Please merge it in master.

**Comment by maxs15** [comment]
Fix deployed in 2.0.1

**Comment by jorgegvallejo** [comment]
> Edit: this can be resolved by adjusting it to:
> ` const animEvt = Animated.event([null, {customY: position}], {useNativeDriver: false});`

I tried this, the warning is gone, but now I get a different error:
`TypeError: animEvt is not a function. (In 'animEvt(evt, state)', 'animEvt' is an instance of AnimatedEvent)`
