### ISSUE TITLE
Can't work well in scrollView

### ISSUE THREAD

**Issue by xu6148152** [maxs15/react-native-modalbox#33]
My rootView is scrollView, and open modal, if i scroll outer of modal, the modal will scroll....

**Comment by maxs15** [comment]
Why don't you render the Modal outside of the scrollView ?

**Comment by xu6148152** [comment]
@maxs15  not, i render the modal inside the scrollview.

**Comment by xu6148152** [comment]
@maxs15 May you offer an example?
If i render it outside of the scrollview, i must using another view as root, if so, my scrollview will not scroll.

**Comment by maxs15** [comment]
Well, I don't know how is designed your code structure but you could do something like that:
```
<View>
  <Modal/>
  <ScrollView>

  </ScrollView>
</View>
```

**Comment by xu6148152** [comment]
@maxs15 
If I using 
```
<View>
  <Modal/>
  <ScrollView>

  </ScrollView>
</View>
```
The views inside ```ScrollView``` will not scroll never.

**Comment by cbilgili** [comment]
For me 
`<View>
  <Modal/>
  <ScrollView>

  </ScrollView>
</View>`

structure worked!

**Comment by fengjiankang** [comment]
I use the code, the scrolView will not work

**Comment by forrest23** [comment]
I use the code,the scrolView and model all worked

**Comment by Donhv** [comment]
thanks u. u save my life @maxs15
