### ISSUE TITLE
RN 0.63 

### ISSUE THREAD

**Issue by zkhbAJUL** [maxs15/react-native-modalbox#330]
Animated.event now requires a second argument for options
<img width="1045" alt="WX20200908-153235@2x" src="https://user-images.githubusercontent.com/42693136/92446537-8b4ce300-f1e8-11ea-8178-57403cb52791.png">

**Comment by aminmeshk** [comment]
I get the same error too

**Comment by jtraub** [comment]
PRs #318, #312 both take care of this warning.

You can merge them to your own fork or use [this fork](https://github.com/maxs15/react-native-modalbox/issues/321#issuecomment-643797782) which already includes #318

**Comment by maxs15** [comment]
Fix published in 2.0.1
