### ISSUE TITLE
Modal doesn't respond to orientation changes

### ISSUE THREAD

**Issue by MossP** [maxs15/react-native-modalbox#34]
Hey @maxs15. Hope you're well.
Little bug I just found: changing the device from portrait to landscape will leave the modal stuck in the orientation that it was when the modal was instantiated.

**Comment by maxs15** [comment]
Thanks @MossP,
I was actually already aware of this bug, but I had an issue with the Dimension that wasn't updated with the new size of the screen..
Will have to look if this is still the case with the new version of RN.

**Comment by rpellerin** [comment]
![out](https://cloud.githubusercontent.com/assets/5323445/12310847/0d6afb1a-ba53-11e5-90e5-b148fc1ea8bc.gif)

A quick demo of the bug

**Comment by MossP** [comment]
np @maxs15. Jus thought I'd let you know.. and thanks for the demo @rpellerin :)

**Comment by maxs15** [comment]
Thanks for the demo, the support of rotations has been added in the last version (1.2.7).
Please check it out ! :)

**Comment by rpellerin** [comment]
Awesome thanks a lot!

**Comment by rpellerin** [comment]
Just tried, works as expected, thank you very much for being so fast at fixing it.

**Comment by maxs15** [comment]
Np, I'm closing the issue.

**Comment by MossP** [comment]
A god among men, @maxs15. I will try this out straight away. Many thanks.
