### ISSUE TITLE
swipeToClose does not like to be changed

### ISSUE THREAD

**Issue by rgoldiez** [maxs15/react-native-modalbox#35]
I'm working on a project that re-uses the same modal component with different behaviors (depending on content) for swipeToClose.  However, swipeToClose (once set) does not play nicely with changes to this property.  

From a quick dig through the code, it looks like the panResponder is created (or not) when the modal mounts and it's not setup to respond based on `componentWillReceiveProps`.  But, it also looks like the pan responder that is created (in the case where `swipeToClose={true}`) is not destroyed when equal to false.

**Comment by maxs15** [comment]
You're right, there is some enhancements to do in order to destroy the pan responder when the swipeToClose property is updated.
Will include a fix in the next release.

**Comment by maxs15** [comment]
This should be fixed in the version [1.2.8](https://github.com/maxs15/react-native-modalbox/releases/tag/v1.2.8).
Let me know if it solves your issue.

**Comment by rgoldiez** [comment]
Thanks... trying to try it.  Is there an updated npm package?

**Comment by maxs15** [comment]
now yes ! ;)

**Comment by rgoldiez** [comment]
Works!  Awesome.  Appreciate the help.

**Comment by maxs15** [comment]
Np, I'm closing the issue

**Comment by votala** [comment]
Year 2021. issue still exist..
