### ISSUE TITLE
Is it worth adding params to open method so we can pass node to render as children,

### ISSUE THREAD

**Issue by gs-akhan** [maxs15/react-native-modalbox#37]
Hi,
I was thinking of enhancing open method to accept param:node . So we can have only one modal and pass things to render it while opening. If It makes sense ? I can send a PR.

thanks :)

**Comment by maxs15** [comment]
Hi @gs-akhan,
Well I think you're looking for the flux pattern, please take a look at libraries such as [redux](https://github.com/rackt/redux), [alt](https://github.com/goatslacker/alt)...

Here is a few steps of how it should work:
1/ You should render the modal component somewhere in your root container that is listening to a ``store``
2/ In the components where you need to display a modal you will just have to call an ``action`` with the component node as parameter.
2/ The action will update the store and trigger an event that will update your container and therefore your modal component.

You could also use a router component like [react-native-router-flux](https://github.com/aksonov/react-native-router-flux) to trigger your modal component.
