### ISSUE TITLE
Issues when using with TabBarIOS from react-native-icons

### ISSUE THREAD

**Issue by jaulz** [maxs15/react-native-modalbox#4]
It seems the height of the modal box is not correct when the modal box is instantiated inside an item of a TabBarIOS. See here at the bottom:
http://tinypic.com/view.php?pic=6eoznk&s=8#.VcLlEvmqpHw

**Comment by maxs15** [comment]
I'm going to push a new version soon that will allow more customisations of the modal.
Maybe it's gonna fix your problem
