### ISSUE TITLE
Slider doesn't work in modal window

### ISSUE THREAD

**Issue by kickboxer** [maxs15/react-native-modalbox#40]
I'm trying to use this component https://github.com/jeanregisser/react-native-slider in modal, but it doesn't work.

I'm using react-native 0.19.0.

**Comment by maxs15** [comment]
Does it fix your problem if you deactivate the swipeToClose property ?

**Comment by yamill** [comment]
I have the same issue. It fixes my problem if I deactivate the swipeToClose property.

Would be nice if I can still have the slider with the swipeToClose activated.

**Comment by maxs15** [comment]
I'll try to fix that in the next release.
What if you specify the swipeArea property in order to restrict the swiping zone, does it work ?

**Comment by yamill** [comment]
Awesome. 
Yeah for now I configured the swipeArea to be a value of 60 so it only allows swiping from the top of the view.

**Comment by maxs15** [comment]
Please check the new version 1.3.1, I fixed the pan responder conflict using react-native-slider as an example.
I included the react-native-slider component in the Example app in order to test it.

**Comment by yamill** [comment]
@maxs15  What if my scene is configured with ```Navigator.SceneConfigs.HorizontalSwipeJump```. How do I prevent it from jumping to the next scene when the modal is present?
