### ISSUE TITLE
Navigator.SceneConfigs.HorizontalSwipeJump disable on Modal?

### ISSUE THREAD

**Issue by yamill** [maxs15/react-native-modalbox#44]
Hey I think this may be a feature request or a simple question...

How would I disable ```Navigator.SceneConfigs.HorizontalSwipeJump``` when the modal is present?

**Comment by maxs15** [comment]
I'm not sure about your question, what do you need exactly ? To know if the modal is displayed ?

**Comment by yamill** [comment]
Sorry my question was confusing. I actually ended up resolving this issue.

This is what was happening:
https://github.com/facebook/react-native/issues/5860

**Comment by maxs15** [comment]
Ok, I'm glad you found a solution :+1:
It doesn't seem to be related to the modalbox though
