### ISSUE TITLE
Possibility to have a default setup of the overlay (floating modal?)

### ISSUE THREAD

**Issue by ahmed1490** [maxs15/react-native-modalbox#45]
Instead of closing the modal absolutely, is it possible to put the modal to have a default absolute positioned bottom value?

For eg: 
![Alt text](http://a2.mzstatic.com/eu/r30/Purple69/v4/ac/78/97/ac789734-9f73-8b9a-5a0b-5e494727a2c8/screen322x572.jpeg)

Here the more options may slide up the modal a little more to reveal more options between the button the the text.

Wondering if modalbox is the right option for something complex like this.

**Comment by maxs15** [comment]
I'm not sure to understand what you exactly want to do but it looks like something that you need to implement on your own.
Shouldn't be too difficult to implement it with the Animated API

**Comment by ahmed1490** [comment]
I managed to do it by changing the height using state :)
