### ISSUE TITLE
Invariant Violation: Expected a component class, got undefined.

### ISSUE THREAD

**Issue by psbanka** [maxs15/react-native-modalbox#5]
The screen-shots look excellent! I'm having a little trouble getting this off the ground, however. When using with RN 0.8.0, I am getting this exception whenever implementing the Modal:

`Invariant Violation: Expected a component class, got undefined.`

**Comment by maxs15** [comment]
Hmmm... you have an undefined component, check in your render method if all the components you are using are properly declared

**Comment by psbanka** [comment]
Ya, sorry. I was being a dork.
