### ISSUE TITLE
Move modal while open

### ISSUE THREAD

**Issue by Pungsnigel** [maxs15/react-native-modalbox#50]
Is there any way to move a modal without closing it? Changing the position does not seem to work. My use case is quite simple: I want to react to keyboard events by moving the modal, when the keyboard is opened, the module should move upwards by the height of the keyboard, and when the keyboard closes, the modal should move back to its original position.

**Comment by maxs15** [comment]
For now the it doesn't support the keyboard but that's a great idea we could implement !

**Comment by Pungsnigel** [comment]
For now, I don't have time to do a pull request, might give it a try soon though. 

For anyone looking for a temporary solution: You can adjust the height of the modal in runtime without closing it. Simply add a transparent component at the bottom of the modal, and adjust the height of the modal by the height of the new component. The effect will be the same as moving the entire modal upwards. Ugly, but it works.
