### ISSUE TITLE
Scroll View 

### ISSUE THREAD

**Issue by DurgaManickam** [maxs15/react-native-modalbox#53]
ScrollView not working with listview inside modal even after specifying the swipeArea .
            <Modal style={[styles.modal3]} position={"center"} ref={"modal3"} swipeToClose=                       
{this.state.swipeToClose} swipeArea={50}>
                  <ScrollView contentContainerStyle={styles.listViewContainer}> 
                       {this._renderTransactionList()}//RENDERING LISTVIEW
                  </ScrollView>
            </Modal>

**Comment by kapv89** [comment]
do you have `flex: 1` on the scroll view?

**Comment by DurgaManickam** [comment]
no , i m not using .. this is my code 
<Modal>
      <ScrollView> 
                  {this._renderTransactionList()} //RENDERING LISTVIEW
       </ScrollView>
</Modal>

**Comment by DurgaManickam** [comment]
Finally listview inside scrollview got worked.Need to specify the **height** for **scrollview**
