### ISSUE TITLE
scroll from top to bottom auto close

### ISSUE THREAD

**Issue by L-Jovi** [maxs15/react-native-modalbox#54]
I set scrollview inside smart modalbox, and when I scroll from top to bottom, modal auto close, I ensure that `swipeToClose={false}`, how could I fix it.

thanks for your time.

**Comment by maxs15** [comment]
Use ``swipearea={50}``

**Comment by L-Jovi** [comment]
I try `swipearea={50}` but also trigger close behaviour when I scroll scrollview

![img](https://gyazo.com/4bf3dd1ca14d3325c418ec46c0e87a5c)

**Comment by maxs15** [comment]
Thanks for this awesome example !
I will add this use case in the example and try to reproduce the issue

**Comment by maxs15** [comment]
In the meantime, you're welcome to check the source, if you find the issue I would gladly accept a PR

**Comment by L-Jovi** [comment]
thanks for your suggestion :)

**Comment by maxs15** [comment]
@L-Jovi I added a test using a ScrollView in the ``Example``folder of the repo.
Couldn't reproduce your issue.. could you please run the example in order to check if you have something different in your configuration.

Thanks 👍

**Comment by L-Jovi** [comment]
@maxs15  thanks for your example :)
so strange, I try almost the same config to your example, it works well, but in my app it will auto close.

now I think it's not the issue of your modal-box, probably from my incorrect logic, so I close this issue.

finally, thanks for your patience and the smart modal box component :)
