### ISSUE TITLE
auto close modal when select DatePickerIOS

### ISSUE THREAD

**Issue by L-Jovi** [maxs15/react-native-modalbox#57]
when I select datetime in `DatePickerIOS`, modal auto close immediately like image below.

how should I fix it?

thanks for your time.

![img](https://i.gyazo.com/f5d91b4f18d3183c05f2f9b9ccc524d6.gif)

**Comment by maxs15** [comment]
What if you deactivate the swipeToClose property, do you have the same issue ?

**Comment by L-Jovi** [comment]
thanks for reply :)

I already set `swipeToClose={false}`, and issue still exist.

I change the open and close behaviour through directly call `refs.modal` instead of `isOpen` property, and it works well now.

I suspect that I didn't use your smart modal box in correct way before, close this issue now.

regards.
