### ISSUE TITLE
Touching on Outside the modal

### ISSUE THREAD

**Issue by DurgaManickam** [maxs15/react-native-modalbox#58]
Touching  outside of the modal ie., touching on overlay should not close the modal ?

**Comment by Thanmai-C** [comment]
How to achieve,touching outside a modal should not close the modal?

**Comment by xstable** [comment]
It's easy, you only have to set ` isDisabled={this.state.modalIsDisabled}` and change the State for your needs. 
Make sure, you use the callback-Method of the setState, to be sure, that the Modal state changed, before you go on with your code.

E.g, if I my Modal-Ref = `this.audioToolbar` I do call this:

```JS
onPress={() => {
              this.setState({ modalIsDisabled: false }, () => { this.audioToolbar.close(); });
            }}
```
