### ISSUE TITLE
Using with ListView, trying to pass data

### ISSUE THREAD

**Issue by philohelp** [maxs15/react-native-modalbox#66]
Great component ! Although I cant figure a correct way to pass data in the modal. I launch a modal from the items of a listView (easy), but then I'd need it to transmit this.rowData.title, this.rowData.content etc. to the component. What should I do ? 

I tried this with a setState approach but with no success :

`<ListView
 dataSource={this.state.dataSource}
 renderRow={(rowData) => <TouchableOpacity onPress={this.setState({name: rowData.name}), this.openModal().bind(this)}>`

Then I did `<Modal props... ><Text>{this.state.name}</Text></Modal>` -> doesn't work.

**Comment by philohelp** [comment]
I found the solution : onPress={this.openModal1.bind(this, rowData)}, it works fine, but is there a more direct way to communicate with the component ?

**Comment by maxs15** [comment]
Yes that's the solution @philohelp, binding the event in the constructor would be nicer in my opinion as well.
I would advise you to learn how react works if you want to be sure how to manage your states: https://facebook.github.io/react/docs/tutorial.html

**Comment by kpatibandla** [comment]
@philohelp - Can you please post sample code snippet for this problem. Thank you.
