### ISSUE TITLE
After install this and follow the steps to setup. Get these errors in Building App 

### ISSUE THREAD

**Issue by kit2000usa** [maxs15/react-native-modalbox#7]
/Users/App/node_modules/react-native-modalbox/node_modules/react-native-overlay/RNOverlay.m
/Users/App/node_modules/react-native-modalbox/node_modules/react-native-overlay/RNOverlay.m:21:44: Cannot find protocol declaration for 'RCTViewNodeProtocol'
/Users/App/node_modules/react-native-modalbox/node_modules/react-native-overlay/RNOverlay.m:23:37: Cannot find protocol declaration for 'RCTViewNodeProtocol'
/Users/App/node_modules/react-native-modalbox/node_modules/react-native-overlay/RNOverlay.m:88:47: Cannot find protocol declaration for 'RCTViewNodeProtocol'
/Users/App/node_modules/react-native-modalbox/node_modules/react-native-overlay/RNOverlay.m:25:12: Property 'reactTag' not found on object of type '__strong id'
/Users/App/node_modules/react-native-modalbox/node_modules/react-native-overlay/RNOverlay.m:26:11: Cannot find protocol declaration for 'RCTViewNodeProtocol'
/Users/App/node_modules/react-native-modalbox/node_modules/react-native-overlay/RNOverlay.m:26:48: Property 'reactSubviews' not found on object of type '__strong id'

**Comment by maxs15** [comment]
What version of react native are you using ?

**Comment by kit2000usa** [comment]
0.10.1

**Comment by maxs15** [comment]
Ok, please use the last version 1.1.4, everything should work now :)
