### ISSUE TITLE
Android back button doesn't close the modal, pops the navigator instead

### ISSUE THREAD

**Issue by namansg** [maxs15/react-native-modalbox#75]
I have setup my android back button to pop the navigator:
React.BackAndroid.addEventListener('hardwareBackPress', () => {
    if (navigator && navigator.getCurrentRoutes().length > 1) {
        navigator.pop();
        return true;
    }
    return false;
});

This also occurs when the modal box is open. Is there any way that I can close the modal box on android back button press?

**Comment by hlynn93** [comment]
Here's what i did, I have a component called Lightbox that uses this modal. Inside that component, I setup the BackAndroid handler like so.
`onBackPress () {
        this.props.onClose()
        return true
    }

    componentDidMount() {
        BackAndroid.addEventListener('hardwareBackPress', this.onBackPress)
    }

    componentWillUnmount() {
        BackAndroid.removeEventListener('hardwareBackPress', this.onBackPress)
    }`

let me know if this works.

**Comment by maxs15** [comment]
PR merged ! closing this issue
