### ISSUE TITLE
[Feature Request] Adding a swipeable area to dismiss the modal

### ISSUE THREAD

**Issue by JonathanWi** [maxs15/react-native-modalbox#8]
Hi @maxs15, found your plugin to work just perfectly & very smoothly so I'm currently using it in my project.

Right now you can either enable or disable the swipe to dismiss feature. My problem is, my modal contains a scrollview, with much more content (ie. comments) than the modal hold. 

I'm left with two solutions : Either I enable the swipe to dismiss, but then I'm unable to scroll inside my scrollView OR I disable the swipe to dismiss - which lead to a perfectly scrollable scrollview - but no ability to dismiss with a simple swipe down.

While looking for modals alternative, I found this : https://github.com/fomahaut/React-Native-Swipeable-Modal#readme

This modal is way less performant than this one but - as you can see - has a "swipeableAreaStyle" which allow the user to customize the are to be swiped.

What do you think?

Cheers

**Comment by maxs15** [comment]
Hey @JonathanWi 
I was actually thinking about adding such a property.
I will try to commit that today if I find some time ;)

**Comment by JonathanWi** [comment]
Awesome! I'll be waiting then, thanks a lot!

**Comment by maxs15** [comment]
Feature released in the version [1.1.5](https://github.com/maxs15/react-native-modalbox/releases/tag/v1.1.5) ;)
