### ISSUE TITLE
Modal doesn't re-render to cover the whole width when re-oriented

### ISSUE THREAD

**Issue by dmeza** [maxs15/react-native-modalbox#82]
This happens because the view with the opacity takes the width and height based on a constant of when the component is created.
var screen = Dimensions.get('window');

![simulator screen shot aug 18 2016 4 31 57 pm](https://cloud.githubusercontent.com/assets/160621/17791612/a3cccf98-6561-11e6-9d27-41de350bb0ad.png)

**Comment by maxs15** [comment]
Erf that's an issue, the size of the modal is based on containerWidth that should be updated when the screen is rotated (in the onContainerLayout method).
I'll try to look at that next week, if you find the issue or want to send a PR let me know 👍 

Thanks

**Comment by edmofro** [comment]
Fixed by #94, can be closed :-)
