### ISSUE TITLE
modal with round corners

### ISSUE THREAD

**Issue by irfanlone** [maxs15/react-native-modalbox#84]
I am trying to figure out a way to add borderRadius to the modal but it doesn't seem to be working.

**Comment by maxs15** [comment]
Doesn't work by adding the borderRadius to the style property of the component ?

**Comment by David-A-RogersHS2** [comment]
Working for me. Although I noticed that if you have elements in your corners, you won't get rounded corners. Dunno why.

**Comment by irfanlone** [comment]
Thanks. It working now, I had some a component covering the rounded corners.
