### ISSUE TITLE
Nothing show 

### ISSUE THREAD

**Issue by uc-asa** [maxs15/react-native-modalbox#88]
I android Its nothing show but IOS works smoothly what can I do

**Comment by uc-asa** [comment]
Its my mistake I have corrected it

**Comment by CodingMonkeyzh** [comment]
@uc-asa I have the some issues in android, how do you fixed it ? maybe,  I make the same mistake as you, but I have't found it

**Comment by uc-asa** [comment]
@CodingMonkeyzh I have provided height and width to modal and also provide in main view which is within modal, It works for me.
