### ISSUE TITLE
Modal fails to open for the second time after close

### ISSUE THREAD

**Issue by kendrickkesley** [maxs15/react-native-modalbox#89]
Hi! I have this problem when I open the modal for the second time, it immediately closes.. But it does not fire onClosed event..

Can you help me to fix this?
I used both of the methods (using isOpen and this.refs.modal.open())

It works for the first time, fails for the second, and works again for the third time..
It seems it fails on even attempts and success on odd attempts

Oh and when I console my custom child component inside the modal, It does indeed fire componentDidMount, but the refs are empty in that component..

Thanks!

**Comment by kendrickkesley** [comment]
Wait, I think the problem does not lie in this component!
I'll investigate further..
Till then, I'm closing this issue

Sorry..

**Comment by gutosanches** [comment]
@kendrickkesley did you get this solved? I'm facing the exact same problem

**Comment by kendrickkesley** [comment]
@gutosanches Hi! I'm sorry I forget how did I fix this issue.. The issue indeed doesn't lie on the library in my case.. I remember that I opened the log (android) with adb logcat command in the cmd and found an error which leads to this issue.
